export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "surface-variant": "#2f3635",
        "primary-fixed": "#61f9e8",
        "primary-container": "#00c7b7",
        "secondary-container": "#0062c1",
        "tertiary-container": "#ff975e",
        "on-primary-fixed": "#00201d",
        "inverse-primary": "#006a61",
        primary: "#00FFB2",
        "on-tertiary-container": "#742f00",
        error: "#FF4444",
        "surface-tint": "#3adccc",
        "on-secondary": "#003064",
        "surface-container-high": "#242b2a",
        "inverse-on-surface": "#2b3230",
        "on-secondary-fixed": "#001b3e",
        "inverse-surface": "#dde4e2",
        "on-background": "#dde4e2",
        tertiary: "#ffbf9f",
        "on-primary": "#003732",
        "on-tertiary-fixed": "#341100",
        "on-surface": "#E8F5EE",
        "secondary-fixed-dim": "#aac7ff",
        "surface-container-lowest": "#090f0e",
        "error-container": "#93000a",
        "surface-container-highest": "#2f3635",
        "on-tertiary": "#552100",
        outline: "#859491",
        "on-primary-container": "#004d46",
        "surface-container-low": "#111714",
        "primary-fixed-dim": "#3adccc",
        "tertiary-fixed": "#ffdbcb",
        "on-secondary-container": "#d3e0ff",
        "on-error-container": "#ffdad6",
        "secondary-fixed": "#d6e3ff",
        "surface-bright": "#333b39",
        "on-secondary-fixed-variant": "#00468d",
        background: "#0A0F0D",
        surface: "#0A0F0D",
        "on-surface-variant": "#8FA896",
        "outline-variant": "#1E2820",
        "surface-container": "#161D19",
        secondary: "#aac7ff",
        "surface-dim": "#0A0F0D",
        "on-primary-fixed-variant": "#005049",
        "tertiary-fixed-dim": "#ffb691",
        "on-tertiary-fixed-variant": "#783100",
        warning: "#FF8C00",
        info: "#4A9EFF",
        "accent-dim": "#00B37D",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-large": "16px",
        "stack-base": "8px",
        gutter: "16px",
        "stack-compact": "4px",
        "container-padding": "24px",
        "sidebar-width": "240px",
        "utility-bar-height": "56px",
      },
      fontFamily: {
        inter: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-lg": [
          "24px",
          {
            lineHeight: "32px",
            letterSpacing: "-0.02em",
            fontWeight: "600",
          },
        ],
        "data-mono": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "body-base": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": [
          "18px",
          {
            lineHeight: "24px",
            letterSpacing: "-0.01em",
            fontWeight: "600",
          },
        ],
        "label-caps": [
          "11px",
          {
            lineHeight: "16px",
            letterSpacing: "0.08em",
            fontWeight: "700",
          },
        ],
      },
    },
  },
  plugins: [],
};
